#include <assert.h>
#include <limits.h>
#include <stdlib.h>
#include <unistd.h>
#include <cstdarg>
#include <vector>
#include <cstdio>
#include <ostream>
#include <fstream>
#include <sstream>
#include <regex>

#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Linker/Linker.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/Cloning.h"

#include <llvm/Analysis/TargetLibraryInfo.h>
#include <llvm/Analysis/TargetTransformInfo.h>

#if LLVM_MAJOR >= 17
#include <llvm/Transforms/IPO/Internalize.h>
#endif

#include "vortex_utils.h"

#include <llvm/IR/Module.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/Support/FileSystem.h>
#include <llvm/Bitcode/BitcodeWriter.h>

#include "pocl.h"
#include "pocl_file_util.h"
#include "pocl_util.h"

#include "LLVMUtils.h"
#include "kernel_args.h"

static int exec(const char* cmd, std::ostream& out) {
  char buffer[128];
  // Clear LD_PRELOAD inherited from parent — when chipstar/HIP preloads
  // POCL's libOpenCL.so to bypass the system ICD loader, an inherited
  // LD_PRELOAD into our forked clang causes LLVM to register CommandLine
  // options twice (parent POCL's libLLVM + clang's own libLLVM) and abort.
  std::string wrapped = std::string("env -u LD_PRELOAD ") + cmd;
  auto pipe = popen(wrapped.c_str(), "r");
  if (!pipe) {
      //throw std::runtime_error("popen() failed!");
      return -1;
  }
  while (!feof(pipe)) {
      if (fgets(buffer, 128, pipe) != nullptr)
          out << buffer;
  }
  return pclose(pipe);
}

void remove_extension(char* filename) {
  char *last_dot = strrchr(filename, '.');
  if (last_dot != NULL) {
    *last_dot = '\0';
  }
}

// Generate the per-kernel KMU entry file for a multi-entry .vxbin. For each
// kernel this emits:
//
//   __vx_tramp_<name> — a vortex.kernel trampoline that runs the
//     once-per-launch args prologue (__vx_kernel_setup) and calls the
//     kernel. The KMU dispatches every CTA to this address (re-supplied per
//     CTA via VX_CSR_CTA_ENTRY); the kernel body inlines into it, so it
//     carries the no-callee-save kernel calling convention.
//   __vx_kentry_<name> — a retained alias of the trampoline. The VXSYMTAB
//     footer records it so the runtime resolves the kernel by its public
//     name via vx_module_get_kernel.
//
// Each kernel is its own entry point; there is no kernel_id switch table.
static std::string generateKernelEntries(
    const llvm::SmallVector<std::string, 8>& funcNames) {
  std::stringstream ss;
  ss << "/* Auto-generated by compile_vortex_program — per-kernel KMU entry\n"
        "   trampolines for a multi-entry .vxbin. Do not edit. */\n"
        "extern void* __vx_kernel_setup(void);\n\n";
  for (const auto& name : funcNames) {
    ss << "extern void " << name << "(void* args);\n"
       << "__attribute__((annotate(\"vortex.kernel\"), used, retain))\n"
       << "void __vx_tramp_" << name << "(void) {\n"
       << "  " << name << "(__vx_kernel_setup());\n"
       << "}\n"
       << "void __vx_kentry_" << name << "(void) "
          "__attribute__((alias(\"__vx_tramp_" << name << "\"), used, retain));\n\n";
  }
  return ss.str();
}

// Store function arguments in a single argument buffer.
static bool createArgumentsBuffer(llvm::Function *function, llvm::Module *module, llvm::SmallVector<std::string, 8>& funcNames) {
  auto &Context = module->getContext();
  const llvm::DataLayout &DL = module->getDataLayout();

  std::string TargetTriple = module->getTargetTriple();
  bool is64Bit = TargetTriple.find("riscv64") != std::string::npos;

  auto I32Ty = llvm::Type::getInt32Ty(Context);
  auto I8Ty = llvm::Type::getInt8Ty(Context);
  auto I8PtrTy = llvm::PointerType::getUnqual(Context);

  // Create new function signature
  auto NewFuncType = llvm::FunctionType::get(function->getReturnType(), {I8PtrTy}, false);
  auto NewFunc = llvm::Function::Create(NewFuncType, function->getLinkage(), function->getName() + "_vortex");
  module->getFunctionList().insert(function->getIterator(), NewFunc);
  NewFunc->takeName(function);

  auto EntryBlock = llvm::BasicBlock::Create(Context, "entry", NewFunc);
  llvm::IRBuilder<> Builder(EntryBlock);

  // Access function arguments
  auto ai = NewFunc->arg_begin();
  auto ArgBuffer = &*ai++;
  ArgBuffer->setName("ArgBuffer");

  unsigned arg_idx = 0;
  unsigned arg_offset = 0;

  llvm::Value* allocated_local_mem = nullptr;

  auto MDS = llvm::MDNode::get(Context, llvm::MDString::get(Context, "vortex.uniform"));

  uint32_t BaseAlignment = is64Bit ? 8 : 4;

  for (auto& OldArg : function->args()) {
    auto ArgType = OldArg.getType();
    auto ArgOffset = llvm::ConstantInt::get(I32Ty, arg_offset);
    llvm::Value* Arg;
    if (pocl::isLocalMemFunctionArg(function, arg_idx)) {
      if (allocated_local_mem == nullptr) {
        // Load __local_size
        auto local_size_ptr = Builder.CreateGEP(I8Ty, ArgBuffer, ArgOffset, "__local_size_ptr");
        auto local_size = Builder.CreateLoad(I32Ty, local_size_ptr, "__local_size");
        arg_offset = ALIGN_OFFSET(arg_offset + 4, BaseAlignment);
        // Call vx_local_alloc(__local_size)
        auto function_type = llvm::FunctionType::get(I8PtrTy, {I32Ty}, false);
        auto vx_local_alloc_func = module->getOrInsertFunction("vx_local_alloc", function_type);
        allocated_local_mem = Builder.CreateCall(vx_local_alloc_func, {local_size}, "__local_mem");
      }
      // Load argument __offset. Recompute the buffer offset: the
      // __local_size slot above advanced arg_offset, but ArgOffset was
      // snapshotted at the top of the loop iteration and is now stale.
      auto OffsetArgOffset = llvm::ConstantInt::get(I32Ty, arg_offset);
      auto offset_ptr = Builder.CreateGEP(I8Ty, ArgBuffer, OffsetArgOffset, OldArg.getName() + "_offset_ptr");
      auto offset = Builder.CreateLoad(I32Ty, offset_ptr, OldArg.getName() + "_offset");
      arg_offset = ALIGN_OFFSET(arg_offset + 4, BaseAlignment);
      // Apply the byte offset into the CTA-local memory block.
      Arg = Builder.CreateGEP(I8Ty, allocated_local_mem, offset, OldArg.getName() + "_byte_ptr");
    } else {
      auto offset_ptr = Builder.CreateGEP(I8Ty, ArgBuffer, ArgOffset, OldArg.getName() + "_offset_ptr");
      Arg = Builder.CreateLoad(ArgType, offset_ptr, OldArg.getName() + "_loaded");
      arg_offset = ALIGN_OFFSET(arg_offset + DL.getTypeAllocSize(ArgType), BaseAlignment);
    }
    auto instr = llvm::cast<llvm::Instruction>(Arg);
    assert(instr != nullptr);
    instr->setMetadata("vortex.uniform", MDS);

    OldArg.replaceAllUsesWith(Arg);
    arg_idx += 1;
  }

  // Move the body of the old function to the new function
  NewFunc->splice(NewFunc->end(), function);

  // Connect the entry block to the first block of the old function
  for (auto& BB : *NewFunc) {
    if (&BB != EntryBlock) {
      Builder.CreateBr(&BB);
      break;
    }
  }

  funcNames.push_back(NewFunc->getName().str());

  return true;
}

static void processKernels(llvm::SmallVector<std::string, 8>& funcNames, llvm::Module *module) {
  llvm::SmallVector<llvm::Function *, 8> functionsToErase;
  for (auto& function : module->functions()) {
    if (!pocl::isKernelToProcess(function))
      continue;
    if (createArgumentsBuffer(&function, module, funcNames))
      functionsToErase.push_back(&function);
  }
  for (auto function : functionsToErase) {
    function->eraseFromParent();
  }
}

int compile_vortex_program(char* sz_program_vxbin, void* llvm_module,
                           unsigned module_slot) {
  int err;

  const char* llvm_install_path = getenv("LLVM_PREFIX");
  if (llvm_install_path) {
    if (!pocl_exists(llvm_install_path)) {
      POCL_MSG_ERR("$LLVM_PREFIX: '%s' doesn't exist\n", llvm_install_path);
      return -1;
    }
    POCL_MSG_PRINT_INFO("using $LLVM_PREFIX=%s!\n", llvm_install_path);
  }

  std::string build_cflags = pocl_get_string_option("POCL_VORTEX_CFLAGS", "");
  if (build_cflags == "") {
    POCL_MSG_ERR("'POCL_VORTEX_CFLAGS' need to be set\n");
    return -1;
  }

  std::string build_ldflags = pocl_get_string_option ("POCL_VORTEX_LDFLAGS", "");
  if(build_ldflags == ""){
    POCL_MSG_ERR("'POCL_VORTEX_LDFLAGS' need to be set\n");
    return -1;
  }

  /* Multi-program contexts (e.g. hybridsort builds bucketsort + mergesort as
   * separate cl_programs) must not all link at the same STARTUP_ADDR, or their
   * device code regions overlap when loaded together (mem_alloc reserve fails).
   * Give program N its own base by shifting the linker's STARTUP_ADDR by
   * N * a generous per-module stride. Slot 0 keeps the default base, so
   * single-program apps link identically. gp/tp are PC-relative and sp is a
   * fixed absolute (VX_MEM_STACK_BASE_ADDR), so no runtime relocation is
   * needed -- the image is self-consistent at whatever base it links to. */
  if (module_slot > 0) {
    const std::string key = "STARTUP_ADDR=";
    size_t p = build_ldflags.find(key);
    if (p == std::string::npos) {
      POCL_MSG_ERR("multi-program load needs '%s' in POCL_VORTEX_LDFLAGS\n",
                   key.c_str());
      return -1;
    }
    size_t v = p + key.size();
    size_t e = build_ldflags.find_first_of(" ,\t", v);
    if (e == std::string::npos) e = build_ldflags.size();
    uint64_t base = strtoull(build_ldflags.substr(v, e - v).c_str(), nullptr, 0);
    const uint64_t stride = 0x01000000ull;  /* 16 MB; kernel images are << this */
    uint64_t addr = base + (uint64_t)module_slot * stride;
    /* Stay below the page-table region (0xF0000000 on rv32). 112 modules is
     * far beyond any real context; guard rather than silently overlap it. */
    if (addr + stride > 0xF0000000ull) {
      POCL_MSG_ERR("module slot %u exceeds code address space\n", module_slot);
      return -1;
    }
    char buf[32];
    snprintf(buf, sizeof(buf), "0x%llx", (unsigned long long)addr);
    build_ldflags.replace(v, e - v, buf);
  }

  char sz_program_bc[POCL_MAX_PATHNAME_LENGTH + 1];
  err = pocl_mk_tempname(sz_program_bc, "/tmp/pocl_vortex_program", ".bc", nullptr);
  if (err != 0)
    return err;

  char sz_program_elf[POCL_MAX_PATHNAME_LENGTH + 1];
  err = pocl_mk_tempname(sz_program_elf, "/tmp/pocl_vortex_program", ".elf", nullptr);
  if (err != 0)
    return err;

  char sz_kernel_entries[POCL_MAX_PATHNAME_LENGTH + 1];
  err = pocl_mk_tempname(sz_kernel_entries, "/tmp/pocl_vortex_entries", ".c", nullptr);
  if (err != 0)
    return err;

  auto module = (llvm::Module *)llvm_module;
  llvm::SmallVector<std::string, 8> kernelNames;
  processKernels(kernelNames, module);

  // Emit the per-kernel KMU entry stubs + trampolines into a generated C
  // file, compiled alongside the kernel bitcode below.
  {
    std::error_code EC;
    llvm::raw_fd_ostream file(sz_kernel_entries, EC, llvm::sys::fs::OF_None);
    if (EC) {
      POCL_MSG_ERR("failed to write %s: %s\n", sz_kernel_entries,
                   EC.message().c_str());
      return -1;
    }
    file << generateKernelEntries(kernelNames);
    file.close();
  }

  {
    std::error_code EC;
    llvm::raw_fd_ostream file(sz_program_bc, EC, llvm::sys::fs::OF_None);
    llvm::WriteBitcodeToFile(*module, file);
    file.close();
  }

  if (POCL_DEBUGGING_ON) {
    std::error_code EC;
    llvm::raw_fd_ostream file("program.ll", EC, llvm::sys::fs::OF_None);
    module->print(file, nullptr);
    file.close();
  }

  {
    std::string clang_path(CLANGCC);
    if (llvm_install_path) {
      clang_path.replace(0, strlen(LLVM_PREFIX), llvm_install_path);
    }

    char sz_kernel_main[POCL_MAX_PATHNAME_LENGTH];
    pocl_get_srcdir_or_datadir (sz_kernel_main, "/lib/CL/devices", "", "/vortex/kernel_main.c");

    std::stringstream ss_cmd, ss_out;
    ss_cmd << clang_path.c_str() << " " << build_cflags << " " << sz_program_bc << " " << sz_kernel_main << " " << sz_kernel_entries << " " << build_ldflags << " -o " << sz_program_elf;
    POCL_MSG_PRINT_LLVM("running \"%s\"\n", ss_cmd.str().c_str());
    int err = exec(ss_cmd.str().c_str(), ss_out);
    if (err != 0) {
      POCL_MSG_ERR("%s\n", ss_out.str().c_str());
      return err;
    }
  }

  if (POCL_DEBUGGING_ON) {
    std::string objdump_path(LLVM_OBJDUMP);
    if (llvm_install_path) {
      objdump_path.replace(0, strlen(LLVM_PREFIX), llvm_install_path);
    }

    std::stringstream ss_cmd, ss_out;
    ss_cmd << objdump_path.c_str() << " -D " << sz_program_elf << " > program.dump";

    POCL_MSG_PRINT_LLVM("running \"%s\"\n", ss_cmd.str().c_str());
    int err = exec(ss_cmd.str().c_str(), ss_out);
    if (err != 0) {
      POCL_MSG_ERR("%s\n", ss_out.str().c_str());
      return err;
    }
  }

  {
    std::string vxbintool_path = pocl_get_string_option ("POCL_VORTEX_BINTOOL", "");
    if (vxbintool_path == ""){
      POCL_MSG_ERR("'POCL_VORTEX_BINTOOL' need to be set\n");
      return -1;
    }
    std::stringstream ss_cmd, ss_out;
    ss_cmd << vxbintool_path << " " << sz_program_elf << " " << sz_program_vxbin;
    POCL_MSG_PRINT_LLVM("running \"%s\"\n", ss_cmd.str().c_str());
    int err = exec(ss_cmd.str().c_str(), ss_out);
    if (err != 0) {
      POCL_MSG_ERR("%s\n", ss_out.str().c_str());
      return err;
    }
  }

  return 0;
}